<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'nama',
'posisi',
'sbu',
'email',
'no_hp',
'nik',
'password' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'nama' => array( 'integrated_edit_field3' ),
'posisi' => array( 'integrated_edit_field4' ),
'sbu' => array( 'integrated_edit_field5' ),
'email' => array( 'integrated_edit_field2' ),
'no_hp' => array( 'integrated_edit_field6' ),
'nik' => array( 'integrated_edit_field' ),
'password' => array( 'integrated_edit_field1' ),
'confirm_aoel3cx' => array( 'integrated_confirm_password' ) ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'register_message' ),
'below-grid' => array( 'register_save',
'back_to_login',
'register_reset' ),
'top' => array( 'register_header' ),
'grid' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field2',
'integrated_edit_field6',
'integrated_edit_field',
'integrated_edit_field1',
'integrated_confirm_password' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'register_message' => 'above-grid',
'register_save' => 'below-grid',
'back_to_login' => 'below-grid',
'register_reset' => 'below-grid',
'register_header' => 'top',
'integrated_edit_field3' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_confirm_password' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_confirm_password' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'register_header' => array( 'register_header' ),
'register_message' => array( 'register_message' ),
'integrated_edit_field' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field2',
'integrated_edit_field6',
'integrated_edit_field',
'integrated_edit_field1' ),
'integrated_confirm_password' => array( 'integrated_confirm_password' ),
'register_reset' => array( 'register_reset' ),
'register_save' => array( 'register_save' ),
'back_to_login' => array( 'back_to_login' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field2',
'integrated_edit_field6',
'integrated_edit_field',
'integrated_edit_field1',
'integrated_confirm_password' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'register' => array( 'gridFields' => array( 'nama',
'posisi',
'sbu',
'email',
'no_hp',
'nik',
'password' ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'register',
'type' => 'register',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'register-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'register_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'register-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'register_save',
'back_to_login' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'register_reset' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'register-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'register_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field2',
'integrated_edit_field6',
'integrated_edit_field',
'integrated_edit_field1',
'integrated_confirm_password' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'register_header' => array( 'type' => 'register_header' ),
'register_message' => array( 'type' => 'register_message' ),
'integrated_edit_field3' => array( 'field' => 'nama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'posisi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'sbu',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'no_hp',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'nik',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'password',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_confirm_password' => array( 'type' => 'integrated_confirm_password',
'field' => 'confirm_aoel3cx',
'orientation' => 0 ),
'register_reset' => array( 'type' => 'register_reset' ),
'register_save' => array( 'type' => 'register_save' ),
'back_to_login' => array( 'type' => 'back_to_login' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'left',
'listTotals' => 1 );
		?>