<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'req_id',
'nik_pemesan',
'nama_pemesan',
'posisi_pemesan',
'sbu_pemesan',
'no_telp_pemesan',
'email_pemesan',
'atasan_langsung',
'jenis_pengajuan',
'alasan',
'beban_sbu',
'status',
'ket_admin' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'req_id' => array( 'import_field' ),
'nik_pemesan' => array( 'import_field1' ),
'nama_pemesan' => array( 'import_field2' ),
'posisi_pemesan' => array( 'import_field3' ),
'sbu_pemesan' => array( 'import_field4' ),
'no_telp_pemesan' => array( 'import_field5' ),
'email_pemesan' => array( 'import_field6' ),
'atasan_langsung' => array( 'import_field7' ),
'jenis_pengajuan' => array( 'import_field8' ),
'alasan' => array( 'import_field9' ),
'beban_sbu' => array( 'import_field10' ),
'status' => array( 'import_field11' ),
'ket_admin' => array( 'import_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'req_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'nik_pemesan',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'nama_pemesan',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'posisi_pemesan',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'sbu_pemesan',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'no_telp_pemesan',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'email_pemesan',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'atasan_langsung',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'jenis_pengajuan',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'alasan',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'beban_sbu',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'status',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'ket_admin',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>