<?php
			$optionsArray = array( 'totals' => array( 'req_id' => array( 'totalsType' => '' ),
'nik_pemesan' => array( 'totalsType' => '' ),
'nama_pemesan' => array( 'totalsType' => '' ),
'posisi_pemesan' => array( 'totalsType' => '' ),
'sbu_pemesan' => array( 'totalsType' => '' ),
'no_telp_pemesan' => array( 'totalsType' => '' ),
'email_pemesan' => array( 'totalsType' => '' ),
'atasan_langsung' => array( 'totalsType' => '' ),
'jenis_pengajuan' => array( 'totalsType' => '' ),
'alasan' => array( 'totalsType' => '' ),
'beban_sbu' => array( 'totalsType' => '' ),
'status' => array( 'totalsType' => '' ),
'ket_admin' => array( 'totalsType' => '' ),
'created_at' => array( 'totalsType' => '' ),
'create_by' => array( 'totalsType' => '' ),
'updated_at' => array( 'totalsType' => '' ),
'update_by' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'req_id',
'nik_pemesan',
'nama_pemesan',
'posisi_pemesan',
'sbu_pemesan',
'no_telp_pemesan',
'email_pemesan',
'atasan_langsung',
'jenis_pengajuan',
'alasan',
'beban_sbu',
'status',
'ket_admin' ),
'exportFields' => array( 'req_id',
'nik_pemesan',
'nama_pemesan',
'posisi_pemesan',
'sbu_pemesan',
'no_telp_pemesan',
'email_pemesan',
'atasan_langsung',
'jenis_pengajuan',
'alasan',
'beban_sbu',
'status',
'ket_admin' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'req_id' => array( 'export_field' ),
'nik_pemesan' => array( 'export_field1' ),
'nama_pemesan' => array( 'export_field2' ),
'posisi_pemesan' => array( 'export_field3' ),
'sbu_pemesan' => array( 'export_field4' ),
'no_telp_pemesan' => array( 'export_field5' ),
'email_pemesan' => array( 'export_field6' ),
'atasan_langsung' => array( 'export_field7' ),
'jenis_pengajuan' => array( 'export_field8' ),
'alasan' => array( 'export_field9' ),
'beban_sbu' => array( 'export_field10' ),
'status' => array( 'export_field11' ),
'ket_admin' => array( 'export_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'req_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'nik_pemesan',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'nama_pemesan',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'posisi_pemesan',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'sbu_pemesan',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'no_telp_pemesan',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'email_pemesan',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'atasan_langsung',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'jenis_pengajuan',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'alasan',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'beban_sbu',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'status',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'ket_admin',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>