<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_detail',
'req_id',
'nik_penumpang',
'nik_ktp',
'nama_penumpang',
'posisi_penumpang',
'sbu_penumpang',
'no_telp_penumpang',
'gender',
'tipe_perjalanan',
'bandara_asal',
'bandara_tujuan',
'maskapai',
'tanggal_penerbangan',
'waktu_berangkat',
'waktu_tiba',
'catatan_khusus',
'bandara_asal_p',
'bandara_tujuan_p',
'maskapai_p',
'tanggal_penerbangan_p',
'waktu_berangkat_p',
'waktu_tiba_p',
'catatan_khusus_p' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_detail' => array( 'import_field' ),
'req_id' => array( 'import_field1' ),
'nik_penumpang' => array( 'import_field2' ),
'nik_ktp' => array( 'import_field3' ),
'nama_penumpang' => array( 'import_field4' ),
'posisi_penumpang' => array( 'import_field5' ),
'sbu_penumpang' => array( 'import_field6' ),
'no_telp_penumpang' => array( 'import_field7' ),
'gender' => array( 'import_field8' ),
'tipe_perjalanan' => array( 'import_field9' ),
'bandara_asal' => array( 'import_field10' ),
'bandara_tujuan' => array( 'import_field11' ),
'maskapai' => array( 'import_field12' ),
'tanggal_penerbangan' => array( 'import_field13' ),
'waktu_berangkat' => array( 'import_field14' ),
'waktu_tiba' => array( 'import_field15' ),
'catatan_khusus' => array( 'import_field16' ),
'bandara_asal_p' => array( 'import_field17' ),
'bandara_tujuan_p' => array( 'import_field18' ),
'maskapai_p' => array( 'import_field19' ),
'tanggal_penerbangan_p' => array( 'import_field20' ),
'waktu_berangkat_p' => array( 'import_field21' ),
'waktu_tiba_p' => array( 'import_field22' ),
'catatan_khusus_p' => array( 'import_field23' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id_detail',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'req_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'nik_penumpang',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'nik_ktp',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'nama_penumpang',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'posisi_penumpang',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'sbu_penumpang',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'no_telp_penumpang',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'gender',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'tipe_perjalanan',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'bandara_asal',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'bandara_tujuan',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'maskapai',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'tanggal_penerbangan',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'waktu_berangkat',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'waktu_tiba',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'catatan_khusus',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'bandara_asal_p',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'bandara_tujuan_p',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'maskapai_p',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'tanggal_penerbangan_p',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'waktu_berangkat_p',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'waktu_tiba_p',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'catatan_khusus_p',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>