<?php
			$optionsArray = array( 'totals' => array( 'bandara_asal' => array( 'totalsType' => '' ),
'bandara_asal_p' => array( 'totalsType' => '' ),
'bandara_tujuan' => array( 'totalsType' => '' ),
'bandara_tujuan_p' => array( 'totalsType' => '' ),
'catatan_khusus' => array( 'totalsType' => '' ),
'catatan_khusus_p' => array( 'totalsType' => '' ),
'gender' => array( 'totalsType' => '' ),
'id_detail' => array( 'totalsType' => '' ),
'maskapai' => array( 'totalsType' => '' ),
'maskapai_p' => array( 'totalsType' => '' ),
'nama_penumpang' => array( 'totalsType' => '' ),
'nik_ktp' => array( 'totalsType' => '' ),
'nik_penumpang' => array( 'totalsType' => '' ),
'no_telp_penumpang' => array( 'totalsType' => '' ),
'posisi_penumpang' => array( 'totalsType' => '' ),
'req_id' => array( 'totalsType' => '' ),
'sbu_penumpang' => array( 'totalsType' => '' ),
'tanggal_penerbangan' => array( 'totalsType' => '' ),
'tanggal_penerbangan_p' => array( 'totalsType' => '' ),
'tipe_perjalanan' => array( 'totalsType' => '' ),
'waktu_berangkat' => array( 'totalsType' => '' ),
'waktu_berangkat_p' => array( 'totalsType' => '' ),
'waktu_tiba' => array( 'totalsType' => '' ),
'waktu_tiba_p' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_detail',
'req_id',
'nik_penumpang',
'nik_ktp',
'nama_penumpang',
'posisi_penumpang',
'sbu_penumpang',
'no_telp_penumpang',
'gender',
'tipe_perjalanan',
'bandara_asal',
'bandara_tujuan',
'maskapai',
'tanggal_penerbangan',
'waktu_berangkat',
'waktu_tiba',
'catatan_khusus',
'bandara_asal_p',
'bandara_tujuan_p',
'maskapai_p',
'tanggal_penerbangan_p',
'waktu_berangkat_p',
'waktu_tiba_p',
'catatan_khusus_p' ),
'exportFields' => array( 'id_detail',
'req_id',
'nik_penumpang',
'nik_ktp',
'nama_penumpang',
'posisi_penumpang',
'sbu_penumpang',
'no_telp_penumpang',
'gender',
'tipe_perjalanan',
'bandara_asal',
'bandara_tujuan',
'maskapai',
'tanggal_penerbangan',
'waktu_berangkat',
'waktu_tiba',
'catatan_khusus',
'bandara_asal_p',
'bandara_tujuan_p',
'maskapai_p',
'tanggal_penerbangan_p',
'waktu_berangkat_p',
'waktu_tiba_p',
'catatan_khusus_p' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_detail' => array( 'export_field' ),
'req_id' => array( 'export_field1' ),
'nik_penumpang' => array( 'export_field2' ),
'nik_ktp' => array( 'export_field3' ),
'nama_penumpang' => array( 'export_field4' ),
'posisi_penumpang' => array( 'export_field5' ),
'sbu_penumpang' => array( 'export_field6' ),
'no_telp_penumpang' => array( 'export_field7' ),
'gender' => array( 'export_field8' ),
'tipe_perjalanan' => array( 'export_field9' ),
'bandara_asal' => array( 'export_field10' ),
'bandara_tujuan' => array( 'export_field11' ),
'maskapai' => array( 'export_field12' ),
'tanggal_penerbangan' => array( 'export_field13' ),
'waktu_berangkat' => array( 'export_field14' ),
'waktu_tiba' => array( 'export_field15' ),
'catatan_khusus' => array( 'export_field16' ),
'bandara_asal_p' => array( 'export_field17' ),
'bandara_tujuan_p' => array( 'export_field18' ),
'maskapai_p' => array( 'export_field19' ),
'tanggal_penerbangan_p' => array( 'export_field20' ),
'waktu_berangkat_p' => array( 'export_field21' ),
'waktu_tiba_p' => array( 'export_field22' ),
'catatan_khusus_p' => array( 'export_field23' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id_detail',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'req_id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'nik_penumpang',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'nik_ktp',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'nama_penumpang',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'posisi_penumpang',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'sbu_penumpang',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'no_telp_penumpang',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'gender',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'tipe_perjalanan',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'bandara_asal',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'bandara_tujuan',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'maskapai',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'tanggal_penerbangan',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'waktu_berangkat',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'waktu_tiba',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'catatan_khusus',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'bandara_asal_p',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'bandara_tujuan_p',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'maskapai_p',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'tanggal_penerbangan_p',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'waktu_berangkat_p',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'waktu_tiba_p',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'catatan_khusus_p',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>