<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_pengajuan_ticket_hdr  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeQueryList"]=true;

		$this->events["BeforeShowList"]=true;

		$this->events["BeforeMoveNextList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before SQL query
function BeforeQueryList(&$strSQL, &$strWhereClause, &$strOrderBy, $pageObject)
{

		$nik = $_SESSION["nik"]; 

$groups = Security::getUserGroups();

if(isset($groups["admin"]) && !empty($nik)) {

    $strWhereClause .= ($strWhereClause ? " AND " : "") .
        "nik_pemesan = " . db_prepare_string($nik);
}
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeQueryList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		$groups = Security::getUserGroups();

if(isset($groups["admin"])){
    $pageObject->hideItem("custom_button");
    $pageObject->hideItem("custom_button1");
    $pageObject->hideItem("custom_button2");
    $pageObject->hideItem("custom_button3");
}
;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		if ($data["status"] == '1') {
    $record["css"] = "background-color:#dbeafe;"; // biru muda
} 
elseif ($data["status"] == '2') {
    $record["css"] = "background-color:#dcfce7;"; // hijau
} 
elseif ($data["status"] == '3') {
    $record["css"] = "background-color:#fef9c3;"; // kuning
} 
elseif ($data["status"] == '4') {
    $record["css"] = "background-color:#fee2e2;"; // merah
} 
elseif ($data["status"] == '5') {
    $record["css"] = "background-color:#ede9fe;"; // ungu
} 
elseif ($data["status"] == '6') {
    $record["css"] = "background-color:#fce7f3;"; // pink
} 
elseif ($data["status"] == '7') {
    $record["css"] = "background-color:#fefce8;"; // cream
}
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
