<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => '˂Create new˃',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => null,
'fullnameField' => 'nama',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'resetDateField' => '˂Create new˃',
'resetTokenField' => '˂Create new˃',
'table' => array( 'connId' => 'sumsel_ticketing_at_localhost',
'table' => 'tbl_users' ),
'userGroupField' => 'nik',
'usernameField' => 'nik',
'userpicField' => '' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'wvput4sWlnQlbMIPW6Rf',
'JWTSecret' => 'tTMNdsGfBj2M6EIUq5gd' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 0,
'hashAlgorithm' => 0,
'changePasswordPage' => true,
'changePwdPage' => false,
'registerPage' => true,
'remindPage' => false,
'remindPasswordPage' => true ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'noreply_ticketsumsel@baramultigroup.co.id',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'mail.baramultigroup.co.id',
'SMTPPort' => 465,
'SMTPUser' => 'noreply_ticketsumsel@baramultigroup.co.id',
'SMTPPassword' => '#T!cketing4390',
'securityProtocol' => 1 ),
'advancedSecurity' => array( 'allowGuestLogin' => true,
'tables' => array( 'admin_members' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_rights' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_users' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'list_airlane' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'list_airport' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'pengajuan_ticket_dtl' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'pengajuan_ticket_hdr' => array( 'mainOwnerIDField' => 'nik_pemesan',
'securityOption' => 0,
'userOwnerIDField' => 'nik' ),
'tbl_code_list' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tbl_users' => array( 'mainOwnerIDField' => 'id',
'securityOption' => 0,
'userOwnerIDField' => 'id' ) ) ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => '',
'table' => '' ),
'lockingTable' => array( 'connId' => '',
'table' => '' ),
'tables' => array(  ),
'loggingMode' => 0,
'loggingFile' => 'audit.log',
'logSecurityActions' => false,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'sumsel-ticketing',
'loginDataSource' => 'tbl_users',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'sumsel-ticketing',
'dpTableConnId' => 'sumsel_ticketing_at_localhost',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => '˂Create new˃',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => null,
'fullnameField' => 'nama',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'resetDateField' => '˂Create new˃',
'resetTokenField' => '˂Create new˃',
'table' => array( 'connId' => 'sumsel_ticketing_at_localhost',
'table' => 'tbl_users' ),
'userGroupField' => 'nik',
'usernameField' => 'nik',
'userpicField' => '' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array(  ) );
?>