<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_ticket_attachments  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["BeforeAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		// ================== AMBIL MASTER ==================
$master = $pageObject->getMasterRecord();

if(!$master){
    error_log("Master record tidak ditemukan");
    return;
}

$req_id        = $master['req_id'];
$email_pemesan = $master['email_pemesan'];
$nama_pemesan  = $master['nama_pemesan'];

date_default_timezone_set('Asia/Jakarta');
$now       = date('Y-m-d H:i:s');
$issued_by = isset($_SESSION['UserName']) ? $_SESSION['UserName'] : 'Admin';

$base_url = 'http://' . $_SERVER['HTTP_HOST'];
$cek_link = $base_url . '/cek-status.php?req_id=' . urlencode($req_id);
// ================== UPDATE STATUS ==================
CustomQuery("UPDATE tbl_pengajuan_ticket_hdr 
    SET status = '5', 
        update_by = '$issued_by', 
        updated_at = '$now' 
    WHERE req_id = '$req_id'");

// ================== EMAIL ==================
if (!empty($email_pemesan)) {

    $subject = '[Sumsel Ticketing] Tiket Telah Diterbitkan - ' . $req_id;

    $body = "
    <html><head><meta charset='UTF-8'></head>
    <body style='font-family:Arial,sans-serif;color:#1f2937'>
      <div style='max-width:620px;margin:32px auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08)'>
        <div style='background:linear-gradient(135deg,#1d4ed8 0%,#3b82f6 100%);padding:32px;text-align:center'>
          <div style='font-size:36px;margin-bottom:8px'>&#x1F3AB;</div>
          <h1 style='margin:0;color:#fff;font-size:22px;font-weight:700'>Tiket Telah Diterbitkan!</h1>
          <p style='margin:8px 0 0;color:#bfdbfe;font-size:14px'>Tiket Anda sudah siap digunakan</p>
        </div>
        <div style='padding:28px 32px'>
          <p style='font-size:15px;margin:0 0 16px'>Halo <strong>" . htmlspecialchars($nama_pemesan) . "</strong>,</p>
					<p style='font-size:14px;color:#6b7280;margin:0 0 24px'>
					Pengajuan tiket Anda telah <strong style='color:#1d4ed8'>diterbitkan</strong> oleh admin.<br>
					Silakan segera <strong>mengunduh (download) tiket Anda</strong> melalui halaman cek status untuk digunakan sesuai kebutuhan perjalanan Anda.
					</p>
          <div style='background:#eff6ff;border:2px dashed #93c5fd;border-radius:12px;padding:18px;text-align:center;margin-bottom:24px'>
            <div style='font-size:12px;color:#1d4ed8;font-weight:600;text-transform:uppercase;margin-bottom:6px'>Nomor Tiket</div>
            <div style='font-size:26px;font-weight:700;color:#1d4ed8'>$req_id</div>
          </div>
          <table style='width:100%;border-collapse:collapse;background:#f9fafb;border-radius:10px;overflow:hidden'>
            <tr style='border-bottom:1px solid #e5e7eb'>
              <td style='padding:10px 14px;font-size:13px;color:#6b7280;width:140px'>Status</td>
              <td style='padding:10px 14px;font-size:13px;font-weight:600;color:#1d4ed8'>Issued</td>
            </tr>
            <tr style='border-bottom:1px solid #e5e7eb'>
              <td style='padding:10px 14px;font-size:13px;color:#6b7280'>Diterbitkan Oleh</td>
              <td style='padding:10px 14px;font-size:13px;font-weight:600;color:#1f2937'>" . htmlspecialchars($issued_by) . "</td>
            </tr>
            <tr>
              <td style='padding:10px 14px;font-size:13px;color:#6b7280'>Tanggal</td>
              <td style='padding:10px 14px;font-size:13px;color:#1f2937'>" . date('d M Y H:i') . "</td>
            </tr>
          </table>
          <div style='background:#eff6ff;border:1.5px solid #93c5fd;border-radius:12px;padding:20px;text-align:center;margin-top:24px'>
					<div style='font-size:14px;font-weight:600;color:#1e3a8a;margin-bottom:12px'>
					Silakan Unduh Tiket Anda di Sini
					</div>
            <a href='$cek_link' style='display:inline-block;background:#1d4ed8;color:#ffffff;text-decoration:none;padding:12px 28px;border-radius:8px;font-size:14px;font-weight:700'>&#x2B07; Download Tiket</a>
            <div style='font-size:12px;color:#6b7280;margin-top:10px'>atau buka: <a href='$cek_link' style='color:#1d4ed8;word-break:break-all'>$cek_link</a></div>
          </div>
        </div>
        <div style='background:#f9fafb;border-top:1px solid #e5e7eb;padding:20px 32px;text-align:center'>
          <p style='margin:0;font-size:12px;color:#9ca3af'>Email ini adalah notifikasi otomatis. Jangan balas email ini.</p>
          <p style='margin:4px 0 0;font-size:12px;color:#9ca3af'>&copy; " . date('Y') . " Sumsel Ticketing</p>
        </div>
      </div>
    </body></html>";

    // 🔥 KIRIM EMAIL VIA PHPRUNNER
    $resultMail = runner_mail(array(
        "to"       => $email_pemesan,
        "subject"  => $subject,
        "htmlbody" => $body,
        "charset"  => "UTF-8"
    ));

    // DEBUG kalau gagal
    if (!$resultMail["mailed"]) {
        error_log("EMAIL GAGAL: " . $resultMail["message"]);
    }
}
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$sqlValues, &$message, $inline, $pageObject)
{

		$values['update_by'] = $_SESSION["nama"];
$values['update_date'] = now();

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
